ca-risken/google

- Makefile
- env_sample.sh
- src/asset/Dockerfile
- src/cloudsploit/Dockerfile
- src/google/Dockerfile
- src/portscan/Dockerfile
- src/scc/Dockerfile
> rm: GOPRIVATE

- src/scc/handler.go
リファクタです。
SCCのAPIですが、InternalFetchを使うことで1件ずつではなく一気に50件データを取得することができました。
> refactor: scc api fetch

- src/scc/main.go
> fix: core addr

- src/google/service.go
スキャンすべき対象へのスキャン要求がなされていない可能性がある場合に、エラーを返すよう修正
> return error when processing invoke scan

- src/portscan/finding.go
- src/portscan/go.mod
- src/portscan/go.sum
- src/portscan/handler.go
TagFinding時にエラーが発生する問題への対応のため、ログを追加します
> Add-portscan-logging

- src/portscan/go.mod
- src/portscan/go.sum
以下の修正を反映させます
ca-risken/common#111
> update portscan module

- src/portscan/go.mod
- src/portscan/go.sum
- src/portscan/handler.go
> Logging portscan result analysis failure

- src/cloudsploit/plugin.go
CloudSploitのスコアがドキュメントの記載と乖離している部分があったため修正します。
> fix: score

- src/asset/asset.go
- src/asset/handler.go
サービスアカウントのステータスがDisabled状態の場合にはスコアを下げる対応です。
> fix: score for disabled SA

- dockers/cloudsploit/Dockerfile
> upgrade: cloudsploit

- go.mod
- go.sum
- pkg/asset/handler.go
- pkg/cloudsploit/handler.go
- pkg/portscan/handler.go
> fix: clear score finding

- pkg/asset/handler.go
- pkg/asset/handler_test.go
assetのデータについて、finding一覧で表示されるDescriptionを見ても、脅威がわかりづらいためもう少し説明を加える。
> fix: asset description

- pkg/scc/handler.go
- pkg/scc/scc.go
> rm: gcp org id

- cmd/asset/main.go
- cmd/cloudsploit/main.go
- cmd/portscan/main.go
- cmd/scc/main.go
> fix: datasource-api

- pkg/asset/handler.go
APIのRateLimitエラーへの緩和策でリクエスト数を抑える調整を行います
> adjust: API request num

- cmd/asset/main.go
- cmd/cloudsploit/main.go
- cmd/portscan/main.go
- cmd/scc/main.go
> rm: finalyzer

- cmd/scc/main.go
- pkg/scc/handler.go
- pkg/scc/scc.go
重大度=LOWを含むかどうかのオプションを追加します（デフォルト=含む）
> add: severity option for scc

- cmd/cloudsploit/main.go
- pkg/cloudsploit/cloudsploit.go
cloudsploitの実行コマンドに、max-old-space-sizeを追加します
> add node options

- pkg/cloudsploit/handler.go
cloudsploit resource nameを変更します。
> fix: cloudsploit resource name

- codebuild/multi-arch/buildspec-image.yml
> fix: go version

- pkg/asset/asset.go
- pkg/asset/handler.go
- pkg/asset/handler_test.go
バケットのPublicAccessPreventionを考慮したパブリック判定にしたい
> add: get bucket attribute

- pkg/scc/finding.go
`put finding error: err=rpc error: code = Unknown desc = description: the length must be no more than 200.`
上記のエラーを解決するための変更。
> [mod]200文字エラー
