src/scc/handler.go
最大50件のfindingが生成されるようにしました。
これにより、findingが大量に検出されてもリソース調整をしなくても大丈夫な状態になります。
=> Put findings per max length

src/google/service.go, src/google/service_test.go
DeleteGCPで関連データを削除する処理を追加（データ不整合が起きてしまうため）
ref https://github.com/ca-risken/internal-community/issues/269
=> fix: delete gcp

src/portscan/finding.go, src/portscan/go.mod, src/portscan/go.sum
`nmapResult.Service`が空文字の場合、`nmapResult.GetTags()`が空文字を要素に持つスライスを返した結果`s.putFindings()`がエラーを返していた事象を解決。
上記の事象がどういう条件で発生するか不明なため、当該データをログに出力するようにしています。
=> Fix blank tag error in portscan

src/portscan/enumerater.go, src/portscan/enumerater_test.go, src/portscan/go.sum, src/portscan/handler.go
portscanでスキャン対象のfirewallルールを取得する処理で、computeのAPIが `SERVICE_DISABLED` だった場合に限り、（Computeサービスを使っておらずAPIが有効化されていないケース）エラー扱いにしないよう修正します。
=> Fix portscan

src/asset/asset.go, src/asset/grpc_client.go, src/asset/handler.go, src/asset/main.go, src/asset/sqs.go
src/asset配下のエラーハンドリング改善しました。
* client生成時のエラーは呼び出し元でハンドリングするために呼び出し元に返すようにしています。
* handleErrorWithUpdateStatusはステータスの更新とエラーのラッピングという二つの責務を持っていたので、見通しをよくするために分割しました。責務に合わせてメソッド名も変更しています。
=> Improve error handling in asset

src/cloudsploit/cloudsploit.go, src/cloudsploit/grpc_client.go, src/cloudsploit/handler.go, src/cloudsploit/main.go, src/cloudsploit/sqs.go
src/cloudsploit配下のエラーハンドリング改善しました。
* client生成時のエラーは呼び出し元でハンドリングするために呼び出し元に返すようにしています。
* handleErrorWithUpdateStatusはステータスの更新とエラーのラッピングという二つの責務を持っていたので、見通しをよくするために分割しました。責務に合わせてメソッド名も変更しています。
=> Improve error handling in cloudsploit

src/portscan/enumerater.go, src/portscan/grpc_client.go, src/portscan/handler.go, src/portscan/main.go, src/portscan/sqs.go
src/portscan配下のエラーハンドリング改善しました。
* client生成時のエラーは呼び出し元でハンドリングするために呼び出し元に返すようにしています。
* handleErrorWithUpdateStatusはステータスの更新とエラーのラッピングという二つの責務を持っていたので、見通しをよくするために分割しました。責務に合わせてメソッド名も変更しています。
* findings登録でエラーが発生した場合、呼び出し元にエラーを返すようにしています。
=> Improve error handling in portscan

src/scc/grpc_client.go, src/scc/handler.go, src/scc/main.go, src/scc/scc.go, src/scc/sqs.go
src/scc配下のエラーハンドリング改善しました。
* client生成時のエラーは呼び出し元でハンドリングするために呼び出し元に返すようにしています。
* handleErrorWithUpdateStatusはステータスの更新とエラーのラッピングという二つの責務を持っていたので、見通しをよくするために分割しました。責務に合わせてメソッド名も変更しています。
=> Improve error handling in scc

src/portscan/go.mod, src/portscan/go.sum, src/portscan/handler.go
common/pkg/portscanのScan失敗時に返すエラーの型を変更したのでその対応です。
確認用に追加した型のエラーは検出されなかったので一律発生したエラーを返すようにしました。
=> Return error when failed to portscan

dockers/cloudsploit/Dockerfile
旧バージョンでスキャンを実行した後にバージョンが最新になってしまうバグがありました。
旧バージョンではspecific_versionに対応しておらず、スキャン後にspecific_versionのデータがクリアされてしまうことが原因となります。
一度、specific_versionに対応した状態で、CloudSploitを前のバージョンに戻してイメージを作成します。（specific_versionに対応済みのもの）
このPRの後に、CloudSploitのバージョンを最新化する更新を入れる予定です。
=> revert: cloudsploit version

cmd/asset/main.go, cmd/scc/main.go, go.mod, go.sum, pkg/asset/asset.go, pkg/asset/handler.go, pkg/scc/handler.go, pkg/scc/scc.go
GCPのAPIで大量にコールが発生する部分にExponentialBackoffを導入します。
- asset
- security command center
asset APIはもともとリトライの仕組みが入ってましたが、独自実装からExponentialBackoffに切り替えます
=> add: exponential backoff

pkg/scc/handler.go, pkg/scc/scc.go
SCC APIのFetchサイズを50 -> 500に増やします。
大量のFindingがある場合に、スキャン速度に影響するため。
=> fix: iteration size

pkg/scc/handler.go, pkg/scc/scc.go
フェッチサイズを増やすことでパフォーマンスがかなり改善したのとCPUメモリ（主にメモリ）消費もそれほどインパクトがなかったので、もう少し増やしてみたいと思います。
また、Datadog用のトレースはSpanが細かいためGCPプロジェクトによってはかなり生成されてしまうのでコストにも影響します。
そこまで細かい単位でのトレースは不要と判断したのでspanの位置を調整します。
=> increase: fetch size

pkg/portscan/enumerater.go
portscanのデータソースで正常形でもresource_nameを出力していたものを削除します
=> fix portscan logging

pkg/scc/handler.go, pkg/scc/scc.go, pkg/scc/scc_test.go
SCCのFinding検索で以下の条件を追加します
- Activeである
- MUTEされてない
非ActiveなFindingが大量に登録されるケースがあり、データが圧迫される可能性があるためActive（かつMuteされてない）なデータのみを取り込むように修正します。
また、その影響でスコアが下がらないFindingのゴミデータが残ってしまうため、クリアスコア処理を追加します。
=> fix: scc filter

pkg/scc/handler.go, pkg/scc/handler_test.go
SCCのFindingデータに情報を追加します
- SCCの詳細URLリンク
- DescriptionにCVE IDやリソース情報
- レコメンド情報の生成条件を修正
=> fix: scc finiding data

pkg/scc/handler.go
SCCのリコメンド修正します。
- リコメンドにプロエジェクト固有のURLをいれるようになったので、Typeの値をカテゴリからFindingの識別子に変更
- SCCのデータでDescriptionの値が決まったフィールドに設定されてないことが多いため、いくつかのフィールドから抽出を試みるように修正
=> fix: scc recommend

pkg/portscan/enumerater.go
スキャン対象のIP Protocolを判別する際に、ca-risken/commonのportscanでは、小文字での判定をしていましたが
gcpのFirewall RuleではProtocolが大文字で出力されるので、修正します
=> fix target protocol

pkg/scc/handler.go
SAキーやインスタンスIDなど人間に優しくない表示では、オペレーション時に調査が必要で大変なのでFindingにアセット情報を追加します。
フィールド名をresourceではなくassetにしたのは、RISKENの表示上なるべく上側に表示されるようにしたかったためです
=> add: SCC asset info

pkg/scc/finding.go, pkg/scc/finding_test.go, pkg/scc/scc.go, pkg/scc/scc_test.go
SCC API v2のサポートです（API v1で取得していたデータも引き続き取得可能です）
https://cloud.google.com/security-command-center/docs/migrate-v2-api?hl=ja
> 2024 年 12 月 9 日以降、組織内で Security Command Center を初めて有効にする場合は、その組織で Security Command Center API のバージョン 2 のみを使用する必要があります。以前のバージョンはサポートされていません。
=> support: SCC API v2

go.mod, go.sum, pkg/asset/handler.go, pkg/asset/handler_test.go, pkg/scc/finding.go
以下の2点のバグ修正です
- タグの文字数64を超過するケースがあってスキャンがエラーになるのでTruncateします
- バケットのバリック判定を修正
- 「組織から継承する」という設定になっていてもパブリックブロックになっているとは限らない
- 実際は組織の設定をみないと判断できないが、一旦除外したい
- デフォルト継承なのでパブリック判定ができなくなっている
=> fix: bugs(tag length & bucket public)

.github/workflows/build-pr-google.yml
googleに関連付けられていたcodebuildを置き換えるためにgithub actionsのワークフローを追加します。
awsやcoreのものとgolangのバージョンを除き、同じ内容です。
=> add: GitHub Actions workflow for building and tagging container on PRs for Google
